
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - bash: echo build first job
  - bash: $(pipelinelevelvariable)
  - bash: $(build.buildnumber)
  - bash: $(build.buildid)
-job: secondjob 

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
